[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pymongo>=4.0.2",
    "python-telegram-bot>=13.11",
    "python-dotenv>=0.19.2",
    "pydantic>=1.9.0",
]
build-backend = "setuptools.build_meta"